Controllers/CasasController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using CasaShow.Controllers;
using CasaShow.Data;
using CasaShow.Models;
using System.Linq;

namespace CasaShow.Controllers
{
    public class CasasController : Controller
    {

         private readonly ApplicationsDbContext database;

        public CasasController (ApplicationsDbContext database) {
                this.database = database;
        }

        public IActionResult CadastrarCasas (){
            return View ();
        }

        public IActionResult Editar (int Id){
           return RedirectToAction ("CadastrarCasas");
       }

       
       public IActionResult Deletar (int ID){
            Casa aux = database.Casas.First (aux => aux.Id == ID);
          database.Casas.Remove(aux);
          database.SaveChanges();
           return RedirectToAction ("CasaseClubes"); 
       }

        [HttpPost]
       public IActionResult Salvar (Casa casa){
            if(casa.Nome != null && casa.Endereço != null){
           database.Casas.Add(casa);  
           database.SaveChanges();
           return RedirectToAction ("CasaseClubes");
       }
       else {
            Response.StatusCode = 400;
            return new ObjectResult (new {msg= "O nome e o endereço da Casa/Clube precisam ser preenchidos"});
       }

       
       
           
       }


        public IActionResult CasaseClubes()  {

           ViewBag.CasaseClubes = database.Casas.ToList();

            return View();
        }



       }






       
      /* public IActionResult Deletar (int ID){
            Show aux = database.Shows.First (aux => aux.Id == ID);
          database.Shows.Remove(aux);
          database.SaveChanges();
           return RedirectToAction ("Proximos"); */
    }

Controllers/ShowController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using CasaShow.Controllers;
using CasaShow.Data;
using CasaShow.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace CasaShow.Controllers
{
   namespace CasaShow.Controllers
{
    public class ShowController : Controller 
    {

     private readonly ApplicationsDbContext database;

        public ShowController (ApplicationsDbContext database) {
                this.database = database;
    
        }
       public IActionResult Cadastrar (){
           ViewBag.CasaseClubes = database.Casas.ToList();
           return View ();

       } 

       public IActionResult Editar (int Id){
           
       return RedirectToAction ("Cadastrar");
        
       }

       
       public IActionResult Deletar (int ID){
            Show aux = database.Shows.First (aux => aux.Id == ID);
          database.Shows.Remove(aux);
          database.SaveChanges();
           return RedirectToAction ("Proximos"); 
       }



        [HttpPost]
       public IActionResult Salvar (Show show){
             if (ModelState.IsValid && show.Nome == null && show.Valor == 0 && show.Hora == null && show.Categoria == null && show.CasaseClubes ==null){
               Show Show = new Show ();
               Show.Nome = show.Nome;
               Show.Valor = show.Valor;
               Show.Hora = show.Hora;
               Show.Categoria = show.Categoria;

               Show.CasaseClubes = database.Casas.First(c => c.Id == show.Aux);
               database.Shows.Add(Show);
               database.SaveChanges();
               return RedirectToAction ("Proximos");
           }
        
       else {
            Response.StatusCode = 400;
            return new ObjectResult (new {msg= "Para cadastrar um evento todos os campos precisam ser preenchidos"});
            
            
           }
       }
      
       
       
        public IActionResult CasaseClubes (){
          var casas = database.Casas.ToList ();
          return View (casas);  
        }
        public IActionResult Proximos()  {

            
            var proximos = database.Shows.Include (p => p.CasaseClubes).ToList ();
            return View(proximos);
         
        }

        public IActionResult Ingressos()  {

            
            var ingressos = database.Shows.Include (p => p.CasaseClubes).ToList ();
            return View(ingressos);
        }
           
           
           public IActionResult Comprar (int Id){
            ViewBag.T = database.Shows.First(i => i.Id == Id);
            return View ();
           
       }

            public IActionResult SalvarIngresso (Ingresso ingressotemp){

               if (ModelState.IsValid){

            Ingresso ingresso = new Ingresso ();

            ingresso.Show = database.Shows.First (i => i.Id == ingressotemp.Aux);
            database.Ingressos.Add (ingresso);
            database.SaveChanges();
            return View ();
           }


               return RedirectToAction ("Proximos");


        
            }
            
           
           
    
    }
}

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CasaShow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
          <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" > 
              <nav class="navbar navbar-light " ></nav>
              
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                 <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <partial name="_LoginPartial" />

                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                 <div class="navbar-collapse collapse">

                            <ul class="nav navbar-nav">



                                <li><img src="/Img/microfone.png" width="70" height="80" ></img></li>

                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" >Home</a>
                        </li>
                            


                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Show" asp-action="Proximos">Shows</a>
                            </li>


                          <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle btn btn-light" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Cadastrar</a>
                        <div class="dropdown-menu">
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item btn btn-light"  href="/Show/Cadastrar" >Eventos</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item btn btn-light" href="/Casas/CadastrarCasas">Casa/Clube</a>
                    
                        </div>
                        
                        </li>
                            
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Casas" asp-action="CasaseClubes">Casas&Clubes</a>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Ingressos">Ingressos <img src="/Img/ingresso.png" width="30" height="30" ></a>

                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contato">Contato</a>


                            
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container"> 
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CasaShow - <a asp-area="" asp-controller="Home" asp-action="Ingressos" Ingressos asp-controller="Home" asp-action="Contato" ></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <br>
    <br>
    <br>
    <br>
    <br>
    
    <center>
    <audio controls>
	<source src="/Img/mix.mp3" type="audio/mpeg" volume="60" autostart="true" loop="true">
	


    </center>
</audio>


</body>
</html>